import img1 from "@/images/projectpageImage1.png";
import img2 from "@/images/projectpageImage2.png";
import img3 from "@/images/projectpageImage3.png";
import img4 from "@/images/projectpageImage4.png";
import img5 from "@/images/projectpageImage5.png";
import img6 from "@/images/projectpageImage6.png";
import nikita from "@/images/nikita.webp"
import arched from "@/images/arched.jpg"
import leena from "@/images/sabya.jpg"
import ramakant from "@/images/ramakant.webp"
import gopali from "@/images/gopali.webp"
import maithali from "@/images/maithali.webp"
import tejas from "@/images/tejas.webp"
import omkar from "@/images/omkar.webp"
import karthik from "@/images/karthik.webp"
import happy from "@/images/happy.webp"
const projectsData = [
  // RESIDENTIAL_DATA

  [
    {
      image: nikita,
      title: "Fluid Project",
      year: "2023",
      project: "RESIDENTIAL",
      client: "Nikita",
      developer: " developer name here",
      location: "Mumbai",
      usage: "Marketing",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: ramakant,
      title: "A Pinch of Paradise",
      year: "2022",
      project: "RESIDENTIAL",
      client: "Ramakant",
      developer: " developer name here",
      location: "Mumbai",
      usage: "Marketing",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: gopali,
      title: "One Influenced",
      year: "2022",
      project: "RESIDENTIAL",
      client: "Gopali",
      developer: " developer name here",
      location: "Surat",
      usage: "Marketing3",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: maithali,
      title: "Time Travellers Home",
      year: "2022",
      project: "RESIDENTIAL",
      client: "Maithali",
      developer: " developer name here4",
      location: "Ahmedabad",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },

    {
      image: leena,
      title: "The Sabya House",
      year: "2022",
      project: "RESIDENTIAL",
      client: "Leena",
      developer: " developer name here4",
      location: "Vadodara",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },

    {
      image: tejas,
      title: "Scandi Space",
      year: "2024",
      project: "RESIDENTIAL",
      client: "Tejas",
      developer: " developer name here4",
      location: "Pune",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: omkar,
      title: "The Rustic Residence",
      year: "2024",
      project: "RESIDENTIAL",
      client: "Omkar",
      developer: " developer name here4",
      location: "Mumbai",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: arched,
      title: "The Minimal Dream",
      year: "2022",
      project: "RESIDENTIAL",
      client: "Kinjal",
      developer: " developer name here4",
      location: "Vadodara",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: happy,
      title: "Classical Chamber",
      year: "2021",
      project: "RESIDENTIAL",
      client: "Happy",
      developer: " developer name here4",
      location: "Vadodara",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: karthik,
      title: "The Arched Villa",
      year: "2022",
      project: "RESIDENTIAL",
      client: "Karthik",
      developer: " developer name here4",
      location: "Hyderabad",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },
  ],

  //ARCHITECTURE_DATA

  [
    {
      image: img3,
      title: "Jaimini and Amit's dream home",
      year: "2019",
      project: "RESIDENTIAL",
      architect: "architect name here",
      interiordesign: "interiormaata",
      developer: " developer name here",
      location: "Ahmedabad",
      usage: "Marketing",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: img2,
      title: "Jaimini and Amit's dream home2",
      year: "2020",
      project: "RESIDENTIAL",
      architect: "architect name here",
      interiordesign: "interiormaata",
      developer: " developer name here",
      location: "Ahmedabad",
      usage: "Marketing",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: img1,
      title: "Jaimini and Amit's dream home3",
      year: "2019",
      project: "RESIDENTIAL",
      architect: "architect name here",
      interiordesign: "interiormaata",
      developer: " developer name here",
      location: "Ahmedabad",
      usage: "Marketing3",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: img4,
      title: "the gray paradise1",
      year: "2022",
      project: "RESIDENTIAL4",
      architect: "architect name here4",
      interiordesign: "interiormaata4",
      developer: " developer name here4",
      location: "Ahmedabad",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },

    {
      image: img5,
      title: "the gray paradise2",
      year: "2022",
      project: "RESIDENTIAL4",
      architect: "architect name here4",
      interiordesign: "interiormaata4",
      developer: " developer name here4",
      location: "Ahmedabad",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },

    {
      image: img6,
      title: "the gray paradise3",
      year: "2022",
      project: "RESIDENTIAL4",
      architect: "architect name here4",
      interiordesign: "interiormaata4",
      developer: " developer name here4",
      location: "Ahmedabad",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },
  ],

  //COMMERCIAL_DATA
  [
    {
      image: img1,
      title: "Jaimini and Amit's dream home",
      year: "2019",
      project: "RESIDENTIAL",
      architect: "architect name here",
      interiordesign: "interiormaata",
      developer: " developer name here",
      location: "Ahmedabad",
      usage: "Marketing",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: img2,
      title: "Jaimini and Amit's dream home2",
      year: "2020",
      project: "RESIDENTIAL",
      architect: "architect name here",
      interiordesign: "interiormaata",
      developer: " developer name here",
      location: "Ahmedabad",
      usage: "Marketing",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: img3,
      title: "Jaimini and Amit's dream home3",
      year: "2019",
      project: "RESIDENTIAL",
      architect: "architect name here",
      interiordesign: "interiormaata",
      developer: " developer name here",
      location: "Ahmedabad",
      usage: "Marketing3",
      studio: "interiromata",
      copyright: "@Copyright",
    },
    {
      image: img4,
      title: "the gray paradise1",
      year: "2022",
      project: "RESIDENTIAL4",
      architect: "architect name here4",
      interiordesign: "interiormaata4",
      developer: " developer name here4",
      location: "Ahmedabad",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },

    {
      image: img5,
      title: "the gray paradise2",
      year: "2022",
      project: "RESIDENTIAL4",
      architect: "architect name here4",
      interiordesign: "interiormaata4",
      developer: " developer name here4",
      location: "Ahmedabad",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },

    {
      image: img6,
      title: "the gray paradise3",
      year: "2022",
      project: "RESIDENTIAL4",
      architect: "architect name here4",
      interiordesign: "interiormaata4",
      developer: " developer name here4",
      location: "Ahmedabad",
      usage: "Marketing4",
      studio: "interiromata",
      copyright: "@Copyright",
    },
  ],
];

export default projectsData;
